// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjaqsgljdtmaltkgiaje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqYXFzZ2xqZHRtYWx0a2dpYWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NDQwMDcsImV4cCI6MjA1ODQyMDAwN30.np-ydMHylbWo3mUfKKnuIIo5KX__exyLMYYMAMrwGK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);